spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: true

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/dates
    username: postgres
    password: 1234


  devtools:
    restart:
      enabled: true
